### ISSUE TITLE
I am very interested in this project. Do I have the opportunity to develop it with you?

### ISSUE THREAD

**Issue by jh2310** [ayinke-llc/malak#11]
I am very interested in this project. Do I have the opportunity to develop it with you?

**Comment by Titi68730** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by jh2310** [comment]
I can use my own development tools, nodejs and go

**Comment by adelowo** [comment]
Hi, 

Thanks a lot but not at this time. The project is still in the really early stages at this time
